//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Language.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days ago.
        /// </summary>
        public static string DaysAgo {
            get {
                return ResourceManager.GetString("DaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hrs.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours ago.
        /// </summary>
        public static string HoursAgo {
            get {
                return ResourceManager.GetString("HoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        public static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in 1 hour.
        /// </summary>
        public static string InOneHr {
            get {
                return ResourceManager.GetString("InOneHr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in 1 min.
        /// </summary>
        public static string InOneMin {
            get {
                return ResourceManager.GetString("InOneMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in 1 sec.
        /// </summary>
        public static string InOneSec {
            get {
                return ResourceManager.GetString("InOneSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to just now.
        /// </summary>
        public static string JustNow {
            get {
                return ResourceManager.GetString("JustNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mins.
        /// </summary>
        public static string Mins {
            get {
                return ResourceManager.GetString("Mins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mins ago.
        /// </summary>
        public static string MinsAgo {
            get {
                return ResourceManager.GetString("MinsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to months.
        /// </summary>
        public static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to months ago.
        /// </summary>
        public static string MonthsAgo {
            get {
                return ResourceManager.GetString("MonthsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms.
        /// </summary>
        public static string Ms {
            get {
                return ResourceManager.GetString("Ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour ago.
        /// </summary>
        public static string OneHrAgo {
            get {
                return ResourceManager.GetString("OneHrAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 min ago.
        /// </summary>
        public static string OneMinAgo {
            get {
                return ResourceManager.GetString("OneMinAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 sec ago.
        /// </summary>
        public static string OneSecAgo {
            get {
                return ResourceManager.GetString("OneSecAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to secs.
        /// </summary>
        public static string Secs {
            get {
                return ResourceManager.GetString("Secs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to secs ago.
        /// </summary>
        public static string SecsAgo {
            get {
                return ResourceManager.GetString("SecsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tomorrow.
        /// </summary>
        public static string Tomorrow {
            get {
                return ResourceManager.GetString("Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yrs.
        /// </summary>
        public static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yrs ago.
        /// </summary>
        public static string YearsAgo {
            get {
                return ResourceManager.GetString("YearsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yesterday.
        /// </summary>
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
